# Generated by Django 5.0.4 on 2024-04-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_expense_day_alter_sales_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2024, 4, 10, 8, 42, 33, 282575, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.CharField(default=datetime.datetime(2024, 4, 10, 8, 42, 33, 283586, tzinfo=datetime.timezone.utc), max_length=80),
        ),
    ]
