# Generated by Django 5.0.4 on 2024-04-11 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_expense_day_alter_sales_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2024, 4, 11, 5, 39, 40, 107753, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.CharField(default=datetime.datetime(2024, 4, 11, 5, 39, 40, 107753, tzinfo=datetime.timezone.utc), max_length=80),
        ),
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
