# Generated by Django 5.0.4 on 2024-04-11 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_expense_day_alter_sales_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2024, 4, 11, 5, 49, 33, 754231, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='category',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.CharField(default=datetime.datetime(2024, 4, 11, 5, 49, 33, 754231, tzinfo=datetime.timezone.utc), max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
